server:
  port: 9001

spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: gYleV6s68WPCBpoaHLclu5I5CZnuf01v
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://192.168.1.16:8080/realms/wagnerpires
  cloud:
    gateway:
      routes:
        - id: hello-api
          uri: http://192.168.1.9:8084
          predicates:
            - Path=/api/hello
          filters:
            - TokenRelay
